In [2]:
import json
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
%matplotlib inline
import glob
from sqlalchemy import create_engine

In [3]:
# file path with glob
path="green P parking"
all_files = glob.glob(path + "/*.json")
all_files

['green P parking\\green-p-parking-2015.json',
 'green P parking\\green-p-parking-2019.json']

In [4]:
li = []
address= []
for filename in all_files:
    green_df = pd.read_json(filename)
    li.append(green_df)
    address.append(['address'])
li

[                                              carparks
 0    {'id': '1', 'address': '20 Charles Street', 'l...
 1    {'id': '3', 'address': '13 Isabella Street', '...
 2    {'id': '5', 'address': '15 Wellesley Street Ea...
 3    {'id': '11', 'address': '21 Pleasant Blvd.', '...
 4    {'id': '12', 'address': '30 Alvin Avenue', 'la...
 ..                                                 ...
 234  {'id': '269', 'address': '1010 Yonge St.', 'la...
 235  {'id': '272', 'address': '775 King Street West...
 236  {'id': '534', 'address': '15 Marine Parade Dri...
 237  {'id': '273', 'address': '20 Erskine Avenue', ...
 238  {'id': '711', 'address': '158 Borough Drive', ...

 [239 rows x 1 columns],
                                               carparks
 0    {'id': '1', 'slug': 'https://parking.greenp.co...
 1    {'id': '3', 'slug': 'https://parking.greenp.co...
 2    {'id': '5', 'slug': 'https://parking.greenp.co...
 3    {'id': '11', 'slug': 'https://parking.greenp.c...
 4    {'id': '12', 'slug': 'https://parking.greenp.c...
 ..                                                 ...
 247  {'id': '829', 'slug': 'https://parking.greenp....
 248  {'id': '831', 'slug': 'https://parking.greenp....
 249  {'id': '833', 'slug': 'https://parking.greenp....
 250  {'id': '834', 'slug': 'https://parking.greenp....
 251  {'id': '835', 'slug': 'https://parking.greenp....

 [252 rows x 1 columns]]

In [5]:
green_p_df= pd.concat(li, axis=0, ignore_index= True)
green_p_df

                                              carparks
0    {'id': '1', 'address': '20 Charles Street', 'l...
1    {'id': '3', 'address': '13 Isabella Street', '...
2    {'id': '5', 'address': '15 Wellesley Street Ea...
3    {'id': '11', 'address': '21 Pleasant Blvd.', '...
4    {'id': '12', 'address': '30 Alvin Avenue', 'la...
..                                                 ...
486  {'id': '829', 'slug': 'https://parking.greenp....
487  {'id': '831', 'slug': 'https://parking.greenp....
488  {'id': '833', 'slug': 'https://parking.greenp....
489  {'id': '834', 'slug': 'https://parking.greenp....
490  {'id': '835', 'slug': 'https://parking.greenp....

[491 rows x 1 columns]

In [7]:
#green_p_df['carparks'].apply(pd.Series)
green_p_df=pd.read_json(r"C:\Users\Preeti\Desktop\home assessment\green P parking\green-p-parking-2019.json")
green_p_df

                                              carparks
0    {'id': '1', 'slug': 'https://parking.greenp.co...
1    {'id': '3', 'slug': 'https://parking.greenp.co...
2    {'id': '5', 'slug': 'https://parking.greenp.co...
3    {'id': '11', 'slug': 'https://parking.greenp.c...
4    {'id': '12', 'slug': 'https://parking.greenp.c...
..                                                 ...
247  {'id': '829', 'slug': 'https://parking.greenp....
248  {'id': '831', 'slug': 'https://parking.greenp....
249  {'id': '833', 'slug': 'https://parking.greenp....
250  {'id': '834', 'slug': 'https://parking.greenp....
251  {'id': '835', 'slug': 'https://parking.greenp....

[252 rows x 1 columns]

In [8]:
parking_id = []
address = []
rate = []
with open(r"C:\Users\Preeti\Desktop\home assessment\green P parking\green-p-parking-2019.json") as json_file:
    data=json.load(json_file)
    for p in data['carparks']:
     parking_id.append(p["id"])
     address.append(p["address"])
     rate.append(p["rate"])
green_p_df=pd.DataFrame({"parking_id":parking_id,
                        "address":address,
                        "rate":rate})    
green_p_df['address'].value_counts()

2225 Lake shore Blvd West (Parks)     5
1 Brimley Road (Bluffer's Park)       3
2700 Eglinton Avenue West             2
2001 Lake Shore Blvd. West (Parks)    2
20 Charles Street East                1
                                     ..
192 Boardwalk Dr                      1
116 Joseph Duggan Rd                  1
118 Sarah Ashbridge Ave               1
116 Winners Circle                    1
7332 Jane St                          1
Name: address, Length: 244, dtype: int64

In [9]:
address_list= list(green_p_df['address'])

In [10]:
address_list= [address.upper() for address in address_list]
address_list

['20 CHARLES STREET EAST',
 '13 ISABELLA STREET',
 '15 WELLESLEY STREET EAST',
 '21 PLEASANT BLVD.',
 '30 ALVIN AVENUE',
 '20 DELISLE AVENUE',
 '716 PAPE AVENUE',
 '351 KEELE STREET',
 '385 PACIFIC AVENUE',
 '101 CEDARVALE AVENUE',
 '72 AMROTH AVENUE',
 '37 QUEEN STREET EAST',
 '670 PAPE AVENUE',
 '75 HOLLY STREET',
 '20 DUNDAS SQUARE',
 '110 QUEEN STREET WEST (NATHAN PHILLIPS SQUARE GARAGE) - REDUCED PARKING - SEPT. TO DEC.',
 '20 CASTLEFIELD AVENUE',
 '7 NORTON AVENUE',
 '91 VIA ITALIA',
 '2 CHURCH STREET (ST. LAWRENCE GARAGE)',
 '14 FULLER AVENUE',
 '111 BROADVIEW AVENUE',
 '125 BURNABY BLVD',
 '85 LEE AVENUE',
 '30 ROEHAMPTON AVENUE',
 '365 LIPPINCOTT STREET',
 '40 YORK STREET',
 '803 RICHMOND STREET WEST',
 '23 BEDFORD PARK AVENUE',
 '9 BEDFORD ROAD ',
 '265 DURIE STREET',
 '20 ST. ANDREW STREET (KENSINGTON GARAGE)',
 '35 BELLEVUE AVENUE',
 '35 ERINDALE AVENUE',
 '405 SHERBOURNE STREET',
 '400 KEELE STREET',
 '695 LANSDOWNE AVENUE',
 '9 EMERSON AVE.',
 '9 SALEM AVENUE',
 '557 PALMERSTON AVENUE',
 '14 ARUNDEL AVENUE',
 '25 FERRIER AVENUE',
 '20 EATON AVENUE',
 '17 EATON AVENUE',
 '265 ARMADALE AVENUE',
 '675 MANNING AVENUE',
 '10 PORTLAND STREET',
 '745 OSSINGTON AVENUE, 16 CARLING AVENUE',
 '15 DENISON AVENUE',
 '251 MACPHERSON AVENUE',
 '51 ABERDEEN AVENUE',
 '1612 DANFORTH AVENUE',
 '74 CLINTON STREET',
 '255 KENNEDY AVENUE',
 '323 RICHMOND STREET EAST',
 '7 BARTLETT AVENUE',
 '912 EGLINTON AVENUE WEST',
 '20 PRESCOTT AVENUE ',
 '77 GOUGH AVENUE',
 '6 SHERWOOD AVENUE',
 '141 GREENLAW AVENUE',
 '31 LANGFORD AVENUE',
 '265 WILLARD AVENUE',
 '376 CLINTON STREET',
 '573 GERRARD STREET EAST',
 '12 WOODYCREST AVENUE',
 '40 LARCH STREET',
 '25 GLENFOREST ROAD',
 '995 EGLINTON AVENUE WEST',
 '18 FERRIER AVENUE',
 '709 MILLWOOD ROAD',
 '1325 QUEEN STREET WEST',
 '30 ST. CLAIR AVENUE WEST',
 '453 SPADINA ROAD',
 '18 OSSINGTON AVENUE',
 '146 HARRISON STREET',
 '117 HAMMERSMITH AVENUE',
 '730 MT. PLEASANT ROAD',
 '737 RHODES AVENUE',
 '151 HIAWATHA ROAD',
 '650 MT. PLEASANT ROAD',
 '653 GERRARD STREET EAST',
 '268 RHODES AVE',
 '1155 KING STREET WEST',
 '166 WOODBINE AVE',
 '192 BOARDWALK DR',
 '116 JOSEPH DUGGAN RD',
 '118 SARAH ASHBRIDGE AVE',
 '116 WINNERS CIRCLE',
 '157 BEATRICE STREET',
 '1675 LAKESHORE BLVD. E. (PARKS)',
 '20 ASHBRIDGES BAY PARK ROAD (PARKS)',
 '15 PRICE ST',
 '1167 EASTERN AVENUE',
 '1141 EASTERN AVENUE',
 '1117 DUNDAS STREET WEST',
 '465 HURON STREET',
 '2001 LAKE SHORE BLVD. WEST (PARKS)',
 '2001 LAKE SHORE BLVD. WEST (PARKS)',
 '1575 LAKE SHORE BLVD. W. (PARKS)',
 '300 REMEMBRANCE DRIVE ',
 '1275 LAKESHORE BLVD. W. (PARKS)',
 '363 ADELAIDE STREET WEST',
 '74 YORKVILLE AVENUE',
 '205 MCCAUL STREET',
 '1445 BATHURST STREET',
 '3354 DUNDAS STREET WEST',
 '87 RICHMOND STREET EAST',
 '789 ST. CLAIR AVENUE WEST',
 '1501 YONGE STREET',
 '34 HANNA AVENUE',
 '80 CLINTON STREET',
 '646 ST. CLAIR AVENUE WEST',
 '105 SPADINA AVENUE',
 '11 KENWOOD AVENUE',
 '110 DOVERCOURT ROAD',
 '31A PARLIAMENT STREET',
 '19 SPADINA ROAD',
 '44 PARLIAMENT STREET',
 '2201 DUNDAS STREET WEST',
 '9 MADISON AVE.',
 '700 ST. CLAIR AVE WEST',
 '9 BONAR PLACE',
 '115 UNWIN AVENUE',
 '1439 DANFORTH AVENUE',
 '31 BLACKTHORN AVE',
 '136 BROADVIEW AVENUE',
 '1670 BAYVIEW AVE',
 '201 CLAREMONT STREET',
 '154 WESTMOUNT AVENUE',
 '1624 QUEEN STREET WEST',
 '4 SPADINA ROAD',
 '94 NORTHCLIFFE BLVD.',
 '45 ABELL STREET',
 '130 ELIZABETH STREET - TORONTO COACH TERMINAL',
 '250 FORT YORK BLVD. ',
 '70 DISTILLERY LANE',
 '271 FRONT STREET EAST',
 '1010 YONGE ST.',
 '800 FLEET STREET',
 '1030 KING STREET WEST - GARAGE ENTRANCE VIA SHANK ST.',
 '242 DANFORTH AVENUE',
 '287 RUSHTON ROAD',
 '838 BROADVIEW AVE.',
 '100 COOPERAGE STREET',
 '83 TANNERY ROAD',
 '40 ROLLING MILLS RD.',
 '51 DOCKSIDE DR. ',
 '1091 EASTERN AVENUE',
 '292 BRUNSWICK AVENUE',
 '373 FRONT STREET EAST',
 '320 TWEEDSMUIR AVENUE',
 '185 QUEENS QUAY EAST',
 '545 LAKE SHORE BOULEVARD WEST',
 '136 WINEVA AVE.',
 '10 KINGSDALE AVENUE',
 '246 BROOKE AVENUE',
 '10 EMPRESS AVENUE',
 '10 HARLANDALE AVENUE',
 '95 BEECROFT ROAD',
 '180 BEECROFT ROAD',
 '1880 AVENUE ROAD',
 '11 FINCH AVENUE WEST',
 '4576 YONGE STREET',
 '3885 YONGE STREET',
 '68 SHEPPARD AVENUE WEST',
 '5667 YONGE STREET',
 '2170 BAYVIEW AVENUE',
 '7 JACKSON AVENUE',
 '11 GRENVIEW BLVD. N.',
 '342 PRINCE EDWARD DRIVE N.',
 '12 WILLINGDON BLVD. - PARTIAL CONSTRUCTION, REDUCED SPACES',
 '9 WILLINGDON BLVD.',
 '934 ROYAL YORK ROAD',
 '140 FIFTH STREET',
 '66 THIRD STREET',
 '128 EIGHTH STREET',
 '105 FOURTH STREET',
 '3239 LAKE SHORE BOULEVARD WEST',
 '120 SIXTH STREET',
 '3220 BLOOR STREET WEST',
 '575 ROYAL YORK ROAD',
 '139 ISLINGTON AVE.',
 'WOOLGAR LANEWAY REAR OF 1124 THE QUEENSWAY',
 '15 PRIMROSE AVENUE',
 '5 DAYTON AVENUE',
 '20 ROYALAVON CRESCENT',
 '7 MONKTON AVENUE',
 '2195 LAKE SHORE BLVD WEST (PARKS)',
 '2225 LAKE SHORE BLVD WEST (PARKS)',
 '2225 LAKE SHORE BLVD WEST (PARKS)',
 '2225 LAKE SHORE BLVD WEST (PARKS)',
 '2225 LAKE SHORE BLVD WEST (PARKS)',
 '2225 LAKE SHORE BLVD WEST (PARKS)',
 '5 COLONEL SAMUEL SMITH PARK DRIVE',
 '65 COLONEL SAMUEL SMITH PARK DRIVE',
 '14 BARKWIN DR.',
 '2300 LAKE SHORE BOULEVARD WEST',
 '15 MARINE PARADE DRIVE',
 '550 MORTIMER AVENUE',
 '1503 BAYVIEW AVENUE',
 '1169 WESTON ROAD',
 '301 SCOTT ROAD',
 '17 RIVERVIEW GARDENS',
 '16 RIVERVIEW GARDENS',
 '168 CHILTERN HILL ROAD',
 '1A MOULD AVENUE',
 '271A SCARLETT ROAD',
 '2054 DUFFERIN STREET',
 '341 OAKWOOD AVENUE',
 '406 OAKWOOD AVENUE',
 '433 ROGERS ROAD',
 '1 SHORTT STREET',
 '1531 EGLINTON AVENUE WEST',
 '2700 EGLINTON AVENUE WEST',
 '2700 EGLINTON AVENUE WEST',
 '2053 DUFFERIN STREET',
 '2623 EGLINTON AVENUE WEST',
 '4 ROSEMOUNT AVENUE',
 '101 GRANGEWAY AVENUE',
 '197 BLANTYRE AVENUE',
 "1 BRIMLEY ROAD (BLUFFER'S PARK)",
 "1 BRIMLEY ROAD (BLUFFER'S PARK)",
 "1 BRIMLEY ROAD (BLUFFER'S PARK)",
 '284 MILNER AVENUE',
 '1530 MARKHAM ROAD - MINOR CAPITAL REPAIRS ONSITE',
 '1940 LAWRENCE AVENUE EAST',
 '100 GRANGEWAY AVENUE',
 '158 BOROUGH DRIVE',
 'KIPLING SOUTH LOT - 400 MUNSTER AVENUE',
 'ISLINGTON MAIN LOT - 3330 BLOOR STREET WEST',
 'ISLINGTON LOMOND LOT - 20 LOMOND DRIVE',
 'KEELE LOT - 400 INDIAN ROAD',
 'WILSON SOUTH LOT - 30 TIPPETT ROAD',
 'WILSON MAIN LOT - 50 WILSON HEIGHTS BLVD',
 'FINCH WEST LOT - 18 HENDON AVE',
 'FINCH EAST - 814 WILLOWDALE AVE - PARTIAL CLOSURE, REDUCED SPACES',
 'LESLIE LOT - 2760 OLD LESLIE STREET',
 'DON MILLS LOT - 1800 SHEPPARD AVE EAST',
 'ELLESMERE LOT - NEAR 1050 ELLESMERE ROAD - CLOSED FOR CONSTRUCTION UNTIL NOVEMBER 2019',
 'LAWRENCE EAST LOT - NEAR 2450 LAWRENCE AVE EAST',
 'KENNEDY SOUTH LOT -155 TRANSWAY CRES',
 'WARDEN NORTH LOT - 705 WARDEN AVE',
 'WARDEN SOUTH LOT - 701 WARDEN AVE',
 'VICTORIA MAIN LOT - 777 VICTORIA PARK AVENUE',
 'KENNEDY NORTH SERVICE ROAD - 2450 EGLINTON AVE EAST',
 'DOWNSVIEW LOT - 415 WILLIAM R ALLEN RD',
 'TRANSIT ROAD LOT - 25 TRANSIT RD',
 '22 FIELDWAY RD',
 '3950 KEELE STREET',
 '2800 STEELES AVE W.',
 '7332 JANE ST']

In [11]:
parking_tags_df= pd.read_csv(r"C:\Users\Preeti\Desktop\home assessment\parking_top20.csv")
parking_tags_df

,infraction_code,infraction_description,location2,count
0,3.0,PARK ON PRIVATE PROPERTY,2075 BAYVIEW AVE,23353
1,5.0,PARK-SIGNED HWY-PROHIBIT DY/TM,20 EDWARD ST,12278
2,257.0,PARK CONTRARY POSTED CONDITION,1 BRIMLEY RD S,11034
3,207.0,PARK MACHINE-REQD FEE NOT PAID,15 MARINE PARADE DR,8204
4,417.0,STAND VEH.-PSGR LD ZN LD/UNLD,273 BLOOR ST W,7799
...,...,...,...,...
445,73.0,STOP-ADJACENT CNTRE STRIP SIDE,80 FRONT ST E,1
446,73.0,STOP-ADJACENT CNTRE STRIP SIDE,638 TRETHEWEY DR,1
447,73.0,STOP-ADJACENT CNTRE STRIP SIDE,505 UNIVERSITY AVE,1
448,73.0,STOP-ADJACENT CNTRE STRIP SIDE,100 FRONT ST W,1
449,437.0,PARK PRIVATE VEHICLE ON SITE,95 THORNCLIFFE PARK DR,1

In [12]:
parking_tags_loc_df= pd.concat([parking_tags_df])
locations= list(parking_tags_df['location2'])
locations

['2075 BAYVIEW AVE',
 '20 EDWARD ST',
 '1 BRIMLEY RD S',
 '15 MARINE PARADE DR',
 '273 BLOOR ST W',
 '42 CHARLES ST E',
 '18 HENDON AVE',
 '19 GRAND TRUNK CRES',
 '100 MAITLAND ST',
 '60 BLOOR ST W',
 '40 ORCHARD VIEW BLVD',
 '1675 LAKE SHORE BLVD E',
 '1873 BLOOR ST W',
 '1155 KING ST W',
 '24 BELLAIR ST',
 '33 COLLEGE ST',
 '244 VICTORIA ST',
 '1090 DON MILLS RD',
 '2 SUSSEX AVE',
 'TROLLEY CRES',
 'ALBERT ST',
 '12 SUDBURY ST',
 '29 IRWIN AVE',
 '70 YORK ST',
 '555 REXDALE BLVD',
 '720 QUEEN ST W',
 '99 ATLANTIC AVE',
 '1155 KING ST W',
 '15 MARINE PARADE DR',
 '15 MARINE PARADE DR',
 '390 COLLEGE ST',
 '74 VICTORIA ST',
 '100 HARRISON GARDEN BLVD',
 '185 FREDERICK ST',
 'PIPER ST',
 '1170 BAY ST',
 '52 STEWART ST',
 '190 ELIZABETH ST',
 '110 EDWARD ST',
 '106 VICTORIA ST',
 'PEARL ST',
 '401 COLLEGE ST',
 '3250 BLOOR ST W',
 '40 ORCHARD VIEW BLVD',
 '148 CUMBERLAND ST',
 '15 GROSVENOR ST',
 '21 ADELAIDE ST W',
 '76 PEARL ST',
 '106 EDWARD ST',
 '50 HENDON AVE',
 '106 EDWARD ST',
 '42 TARLTON RD',
 '1235 BAY ST',
 '555 REXDALE BLVD',
 '150 ELIZABETH ST',
 '5 ST JOSEPH ST',
 'ROWANWOOD AVE',
 '45 ABELL ST',
 '200 ELIZABETH ST',
 '7 NORTON AVE',
 '5 COLONEL SAMUEL SMITH PARK DR',
 '82 PETER ST',
 'OLD BREWERY LANE',
 '25 CAPREOL CRT',
 '273 BLOOR ST W',
 'WYATT AVE',
 '53 ST PAUL ST',
 '38 ORCHARD VIEW BLVD',
 '329 CHAPLIN CRES',
 '80 GROSVENOR ST',
 '21 HILLCREST AVE',
 '11 WILLISON SQ',
 '410 COLLEGE ST',
 '26 MARKHAM ST',
 '5 BROOKMOUNT RD',
 'OLD MILL RD',
 '280 SIMCOE ST',
 '125 BREMNER BLVD',
 'DEWSON ST',
 '100 PRINCES BLVD',
 '4 EVELYN WIGGINS DR',
 '212 GOWAN AVE',
 '21 HENDON AVE',
 'QUEENS WHARF RD',
 '180 DUNDAS ST W',
 '8 PALMERSTON AVE',
 '244 VICTORIA ST',
 '40 SCOLLARD ST',
 '20 EDWARD ST',
 '1 BRIMLEY RD S',
 '1873 BLOOR ST W',
 '168 PRINCESS ST',
 '25 BRUCEWOOD CRES',
 'DOURO ST',
 '215 MAVETY ST',
 'MELINDA ST',
 '100 QUEEN ST W',
 '40 ORCHARD VIEW BLVD',
 '271 FRONT ST E',
 '43 ELM AVE',
 '31A PARLIAMENT ST',
 'JAMES ST',
 '11 WINDSOR ST',
 '256 CENTENNIAL PARK RD',
 '207 FRONT ST E',
 '36 BRENTWOOD RD N',
 '63 ROEHAMPTON AVE',
 '211 RANDOLPH RD',
 'WHYTOCK AVE',
 '48 MICMAC CRES',
 'ST LUKE LANE',
 '201 CARLAW AVE',
 '70 DAN LECKIE WAY',
 '15 PROVOST DR',
 '640 ROSELAWN AVE',
 'DORIS AVE',
 'COLLEGE ST',
 '21 HENDON AVE',
 '40 ORCHARD VIEW BLVD',
 '70 FERMANAGH AVE',
 '271 FRONT ST E',
 '227 VICTORIA ST',
 '249 QUEENS QUAY W',
 '143 DANFORTH AVE',
 '70 DISTILLERY LANE',
 '65 LILLIAN ST',
 '21 COLLEGE ST',
 '20 TARSUS CRES',
 '101 DUNDALK DR',
 '1 BRIMLEY RD',
 '1 MICHAEL POWER PL',
 '127 RONCESVALLES AVE',
 '142 CUMBERLAND ST',
 '2300 YONGE ST',
 '8 PALMERSTON AVE',
 '60 YONGE ST',
 '55 HYMUS RD',
 '31 ROXTON RD',
 '1155 KING ST WEST',
 '167 DANFORTH AVE',
 '29 ST EMILION WAY',
 'DORIS AVE',
 '1873 BLOOR ST W',
 '27 SHERBOURNE ST N',
 '1 JAMES ST',
 'LYNN WILLIAMS ST',
 '150 DAN LECKIE WAY',
 'HOUSEY ST',
 '249 DUFFERIN ST',
 '8 PALMERSTON AVE',
 '77 ADELAIDE ST W',
 '1700 WILSON AVE',
 '834 GERRARD ST E',
 '410 COLLEGE ST',
 '1005 BRIMLEY RD',
 '2625 WESTON RD',
 '4700 KEELE ST',
 '132 CUMBERLAND ST',
 '67 DUNCANNON DR',
 '171 HURON ST',
 '24 BELLAIR ST',
 '52 HENRY ST',
 '65 LILLIAN ST',
 'FINCH AVE W',
 'WYATT AVE',
 '800 BAY ST',
 '77 ADELAIDE ST W',
 '2075 BAYVIEW AV',
 '255 KENNEDY AVE',
 '390 BAY ST',
 '330 BAY ST',
 '1140 QUEEN ST E',
 '1170 BAY ST',
 '3401 DUFFERIN ST',
 '2645 KIPLING AVE',
 '58 HOWLAND AVENUE',
 '675 MANNING AVE',
 '410 COLLEGE ST',
 'QUEENS QUAY E',
 '620 BLOOR ST W',
 '10 HARLANDALE AV',
 '56 WARREN RD',
 'ADELAIDE ST W',
 '1168 DUNDS ST W',
 '520 BLOOR ST W',
 '500 FLEET ST',
 '405 SHERBOURNE ST',
 '355 SPADINA AVE',
 '30 TIPPET RD',
 '20 EATON AVE',
 '941 PROGRESS AVE',
 '799 MILNER AVE',
 '2 ADELAIDE ST W',
 '40 ROLLING MILLS RD',
 '501 KINGTON RD',
 '363 ADELAIDE ST WEST',
 '265 ARMADALE AVE',
 '4576 YONGE ST',
 '271 FRONT ST EAST',
 '23 BEDFORD PARK AVE',
 '691 BLOOR ST WEST',
 '110 DOVERCOURT RD',
 '1117 DUNDAS STREET WEST',
 '150 DAN LECKIE WAY',
 '20 DELISLE AVE',
 '1155 KING ST W',
 '100 QUEEN ST W',
 '49 FELSTEAD AVE',
 '99 GERRARD ST E',
 'HURON ST',
 'LA PLANTE AVE',
 'ORDE ST',
 'ST NICHOLAS ST',
 '109 WILTON ST',
 '115 FELSTEAD AVE',
 '116 FELSTEAD AVE',
 '137 DRAYTON AVE',
 '143 WESTMORELAND AVE',
 '2 BELLWOODS PK',
 '399 BELSIZE DR',
 '43 HANNA AVE',
 '559 COLLEGE ST',
 '79 HARBORD ST',
 '67 YONGE ST',
 '99 KINGSMOUNT PARK RD',
 'CHISHOLM AVE',
 'DOCKSIDE DR',
 'GERRARD ST E',
 '172 BROADVIEW',
 '433 ROGERS RD',
 '585 UNIVERSITY AVE',
 '743 PAPE AVE',
 '150 CHARLES ST W',
 '220 BAY ST',
 '1 BYNG AVE',
 '800 BOROUGH DR',
 '90 EGLINTON AVE E',
 '51 BULWER ST',
 '150 DAN LECKIE WAY',
 '4190 FINCH AVE E',
 '35 BELLEVUE AVE',
 '364 RICHMOND ST W',
 '411 COLLEGE ST',
 '600 BAY ST',
 '90 ADELAIDE ST W',
 'SHERBOURNE ST',
 '112 EARL PL',
 '265 MAIN ST',
 '401 COLLEGE ST',
 '800 LANSDOWNE AVE',
 '96 BEVERLEY ST',
 '1750 FINCH AVE E',
 '7 JONES AVE',
 '5215 FINCH AVE EAST',
 '4 WHITAKER AVE',
 'BVWJ021',
 "QUEEN'S PLATE DR",
 '65 COLONEL SAM SMITH PARK DR',
 '135 FORT YORK BLVD',
 '520 BLOOR ST W',
 '90 ADELAIDE ST',
 'JARVIS ST',
 '15 MARINE PARADE DR',
 '1500 WOODBINE AVE',
 '200 BALLIOL ST',
 '317 ADELAIDE ST W',
 '35 BULWER ST',
 '363 SPADINA AVE',
 'WIDDICOMBE HILL BLVD',
 '2252 DUNDAS ST W',
 '77 YORE RD',
 '35 ERINDALE AVE',
 '23 BEDFORD PK AVE',
 '186 LAUDER AV',
 '1030 KING ST W',
 '1025 SCARLETT RD',
 '75 GRENOBLE DR',
 'HARBORD ST',
 '76 LEWIS ST',
 '76 FOREST MANOR RD',
 '613 KING ST W',
 '49 WINDHILL CRES',
 '34 ELWAY CT',
 '17 RAMEAU DR',
 '14 MUNRO PARK AVE',
 'HUMBER BAY PARK EAST',
 'ALBERT ST',
 '7 BRISTOL AVE',
 '159A LAPPIN AVE',
 '99 CAMERON ST',
 '95 PRINCE ARTHUR AVE',
 '2765 ISLINGTON AVENUE',
 '70 DISTILLERY LANE',
 '65 EMMETT AVE',
 '1 BIGGIN CRT',
 '3330 BLOOR ST W',
 '31A PARLIAMENT ST',
 '773 BROADVIEW',
 '700 UNIVERSITY AVE',
 '621 OSSINGTON AVE',
 '62 DUNDAS ST E',
 '48 WHITEBRED CRESCENT',
 '41 BASIN ST',
 '301 KING ST W',
 '26 FORT YORK BLVD',
 '226 QUEEN ST W',
 '187 LEYTON AVE',
 '15 PROVOST DR',
 '1039 WOODBINE AV',
 '2 BRAHMS AVE',
 '175 TORYORK DR',
 '3420 KINGSTON RD',
 '30 FALSTAFF AVE',
 '1750 FINCH AVE E',
 '89 WILLCOCKS ST',
 '83 PEARS AVE',
 '707 ST CLAIR AVE W',
 '63 BELLEVUE AVE',
 '10 STADIUM RD',
 '1 LEONARD AVE',
 '1534 EGLINTON AVE W',
 'YONGE ST',
 '699 ST CLAIR AVE W',
 '60 ST GEORGE ST',
 '510 B',
 '500 REXDALE BLVD',
 '500 KING ST W',
 '5 LANARK AVE',
 '410 COLLEGE ST',
 '401 COLLEGE ST',
 '295 ADELAIDE ST W',
 '2625 WESTON RD',
 '2625 WESTO RD',
 '2245 ISLINGTON AVE',
 '1530 ALBION RD',
 '15 VIEWCREST CIR',
 '1390 JANE ST',
 '11 VICTORY DR',
 '120 FRONT ST E',
 '142 COLLIER ST',
 '38 MCGILL ST',
 '61 WALMSLEY BLVD',
 '605 ROGERS RD',
 '580 COMMISSIONERS ST',
 '56 YONGE ST',
 '5453 YONGE ST',
 '51 RIVERDALE AVE',
 '455 FRONT ST E',
 '41 ANTRI CR',
 '341 QUEEN ST W',
 '1904 EGLINTON AVE W',
 '320 QUEEN ST W',
 '312 QUEEN ST W',
 '31 SPRINGHURST AVE',
 '3 WOODLOT CRES',
 '287 ASHDALE AVE',
 '24 BELLWOODS AVE',
 '23 BERNARD AVE',
 '2 1/2 PALMERSTON AVE',
 '613 KING ST W',
 '100 KING ST W',
 '120 BREMNER BLVD',
 '2397 BLOOR ST W',
 '363 KING ST W',
 '2342 BLOOR ST W',
 '1807 EGLINTON AVE',
 '1516 DUNDAS ST W',
 '150 DAN LECKIE WAY',
 '1352 QUEEN ST E',
 '1170 DUNDAS ST W',
 '1102 BLOOR ST W',
 '5915 YONGE ST',
 '502 SPADINA AVE',
 '700 LAWRENCE AVE W',
 '1305 LAWRENCE AVE W',
 '289 DNFORTH AVE',
 '2236A KINGSTON RD',
 'LANEWAY BETWEEN BATHURST ST',
 'KENNEDY RD',
 '31 MERCER ST',
 '50 HILLSBORO AVE',
 '34 WESTERN BATTERY RD',
 '77 ADELAIDE ST W',
 '14 HANSON RD',
 '2175 QUEEN ST E',
 '265 DURIE ST',
 '40 EDINBURGH DR',
 '2560 LAKE SHORE BLVD W',
 '1 DEWBOURNE AVE',
 '115 HAREWOOD AVE',
 'DUNDAS ST E',
 '273 BLOOR ST W',
 '220 DANFORTH AVE',
 '220 BLOOR ST W',
 '2170 BAYVIEW AV',
 '3145 LAKE SHORE BOULEVARD WEST',
 '20 DELISLE AVE',
 '30 ST DENNIS DR',
 '3145 LAKE SHORE BLVD W',
 '1550 EGLINTON AVE W',
 '1227 DUNDAS STREET WEST',
 '282 DOVERCOURT RD',
 '1971 QUEEN ST E',
 '1546A EGLINTON AVE W',
 '2425 BLOOR ST W',
 '2365 BLOOR ST W',
 '246 BROOKE AVE',
 '2362 BLOOR ST W',
 '121 DANFORTH AVE',
 '100 FRONT ST W',
 'YORK ST',
 'RIVER ST',
 'SUMMERHILL GDNS',
 'LESLIE STREET',
 '60 LAUREL AVE',
 '60 COLBORNE ST',
 '403 DELAWARE AVE',
 '25 THE ESPLANADE',
 '20 MARKET ST',
 '195 ST CLAIR AVE W',
 '35 SARANAC BLVD',
 '947 KINGSTON RD',
 '58 MACAULAY AVE',
 '534 EGLINTON AVE W',
 '4950 YONGE ST',
 '273 BLOOR ST W',
 '265 WILLARD AVE',
 '461 UNIVERSITY AVE',
 '7 LOVEKIN GRV',
 'LAWRENCE AVE E',
 'CHERRY ST',
 '2273 BLOOR ST W',
 '2186 BLOOR ST W',
 '187 RONCESVALLES AVE',
 '16 LAIDLAW ST',
 '1585 DUNDAS ST W',
 '1205 BLOOR ST W',
 '25 THE ESPLANADE',
 '2161 QUEEN ST E',
 '228 RONCESVALLES AVE',
 '100 BRENOBLE DR',
 '110 EDWARD ST',
 '101 CUMBERLAND ST',
 '1 OAK ST',
 'RICHMOND ST E',
 '80 FRONT ST E',
 '638 TRETHEWEY DR',
 '505 UNIVERSITY AVE',
 '100 FRONT ST W',
 '95 THORNCLIFFE PARK DR']

In [13]:
common_address_locations=[]
coomon_address_list=[]
for address in address_list:
    for location in locations:
        if str(location) in address and str(location) not in common_address_locations:
            common_address_locations.append(location)
            coomon_address_list.append(address)

In [14]:
print(len(common_address_locations))
print(len(coomon_address_list))

33
33

In [15]:
green_p_df['location2']= address_list

In [16]:
green_p_df.head()

,parking_id,address,rate,location2
0,1,20 Charles Street East,$2.50 / Half Hour,20 CHARLES STREET EAST
1,3,13 Isabella Street,$3.00 / Half Hour,13 ISABELLA STREET
2,5,15 Wellesley Street East,$3.00 / Half Hour,15 WELLESLEY STREET EAST
3,11,21 Pleasant Blvd.,$3.00 / Half Hour,21 PLEASANT BLVD.
4,12,30 Alvin Avenue,$3.50 / Half Hour,30 ALVIN AVENUE

In [17]:
comon_address_df= pd.merge(green_p_df,parking_tags_df,on='location2')
comon_address_df

,parking_id,address,rate,location2,infraction_code,infraction_description,count
0,204,1117 Dundas Street West,$1.50 / Half Hour,1117 DUNDAS STREET WEST,302.0,PAR PARK-R OF VEH NOT OPP MTR,1
1,267,70 Distillery Lane,$2.25 / Half Hour,70 DISTILLERY LANE,311.0,PARK-FEE NOT PD FOR TIME USED,4
2,267,70 Distillery Lane,$2.25 / Half Hour,70 DISTILLERY LANE,34.0,STAND VEHICLE SIGNED HIGHWAY 2,1